# Generated by Django 2.0.3 on 2018-09-18 10:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogauthor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField(max_length=300)),
                ('submitted_date', models.DateTimeField(default=datetime.datetime(2018, 9, 18, 10, 36, 31, 186580, tzinfo=utc))),
            ],
            options={
                'ordering': ('submitted_date',),
            },
        ),
    ]
