# Generated by Django 2.0.3 on 2018-09-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.FileField(blank=True, upload_to='testimonial'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='skill',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
